splash = false
wallpaper {
    monitor = DP-4
    path = ~/.config/hypr/wallpapers/beksinski_man.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-2
    path = ~/.config/hypr/wallpapers/beksinski_man.jpg
    fit_mode = cover
}

