# ~/.tmux.conf

unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Fix Vim ESC delay
set -sg escape-time 0

# Increase scrollback buffer
set -g history-limit 50000

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Apperence
set -g status-style 'bg=#d79921 fg=#282828'
set -g status-right-length 50
set -g status-right '#{=21:pane_title} '
